### ISSUE TITLE
error

### ISSUE THREAD

**Issue by lite0n** [NoahGdev/iCloud-Generator#1]
iCloud-Generator-main % python main.py
Traceback (most recent call last):
  File "/Users//Downloads/iCloud-Generator-main/main.py", line 10, in <module>
    from src.iCloud import iCloud
  File "/Users/Downloads/iCloud-Generator-main/src/iCloud.py", line 2, in <module>
    import requests
  File "/Users//Library/Python/3.9/lib/python/site-packages/requests/__init__.py", line 43, in <module>
    import urllib3
  File "/Users/Library/Python/3.9/lib/python/site-packages/urllib3/__init__.py", line 38, in <module>
    raise ImportError(
ImportError: urllib3 v2.0 only supports OpenSSL 1.1.1+, currently the 'ssl' module is compiled with LibreSSL 2.8.3. See: https://github.com/urllib3/urllib3/issues/2168

**Comment by NoahGdev** [comment]
Hey, maybe you have requests downloaded already? 

if so, update with:
```bash
pip install -U requests
```

I have also updated the requirements.txt file to include the versions that I use.

Let me know if you have any more issues. You can also DM me on discord: N◎AH#0001 (801636548218191893)
